Metrics/AbcSize:
  Max: 31

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Exclude:
    - lib/awskeyring_command.rb
    
Metrics/MethodLength:
  Max: 16

Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
    - aws-keychain-util.gemspec

AllCops:
  Exclude:
    - bin/*
