---
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 20

Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile

AllCops:
  Exclude:
    - bin/*
