---
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/AbcSize:
  Max: 20

Bundler/GemComment:
   Enabled: false
   Include:
     - Gemfile

AllCops:
  Exclude:
    - bin/*
